apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      robusta: playground-team
  template:
    metadata:
      labels:
        robusta: playground-team
    spec:
      containers:
      - name: team
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_username
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_host
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: passwords
                  key: postgres_password
        image: robusta:playground-team 
---
apiVersion: v1
kind: Service
metadata:
  name: team-entrypoint-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    robusta: playground-team	
  ports:
  - protocol: TCP
    port: 1010
    targetPort: 4345
    name: http
