apiVersion: apps/v1
kind: Deployment
metadata:
  name: tournament-microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      robusta: playground-tournament
  template:
    metadata:
      labels:
        robusta: playground-tournament
    spec:
      containers:
      - name: tournament
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_username
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_host
          - name: POSTGRES_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: passwords
                  key: postgres_password
        image: robusta:playground-tournament 
---
apiVersion: v1
kind: Service
metadata:
  name: tournament-entrypoint-loadbalancer
  namespace: default
spec:
  type: LoadBalancer
  selector:
    robusta: playground-tournament
  ports:
  - protocol: TCP
    port: 1011
    targetPort: 4346
    name: http

